# Generated by Django 4.2.4 on 2023-08-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_delete_extendeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='lastlogout',
        ),
    ]
