# Generated by Django 4.2.4 on 2023-10-04 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=255)),
                ('customer', models.CharField(max_length=255)),
                ('analysis_type', models.CharField(choices=[('general', 'General'), ('thermoforming_verification', 'Thermoforming Verification'), ('thermoforming_plug', 'Thermoforming Plug'), ('thermoforming_cad', 'Thermoforming CAD')], default='general', max_length=30)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('simulating', 'Simulating'), ('aborted', 'Aborted'), ('rejected', 'Rejected')], default='saved', max_length=30)),
                ('report_name', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_contact_for', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_analysis', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThermoformingCavityParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('round', 'Round'), ('oblong', 'Oblong')], default='round', max_length=10)),
                ('profile', models.CharField(choices=[('profile1', 'Profile 1'), ('profile2', 'Profile 2'), ('profile3', 'Profile 3')], default='profile1', max_length=10)),
                ('w', models.FloatField()),
                ('c1', models.FloatField()),
                ('l', models.FloatField()),
                ('c2', models.FloatField()),
                ('depth', models.FloatField()),
                ('wall_angle', models.FloatField()),
                ('r', models.FloatField()),
                ('rb', models.FloatField()),
                ('rf', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ThermoformingProcessParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laminate_material', models.CharField(choices=[('amsky_305', 'Amsky 305')], max_length=50)),
                ('lid_material', models.CharField(choices=[('amsky_70', 'Amsky lid 70')], max_length=50)),
                ('contact', models.CharField(choices=[('kinematic', 'Kinematic'), ('penalty', 'Penalty')], default='kinematic', max_length=20)),
                ('temperature', models.FloatField(default=125)),
                ('pressure', models.FloatField(default=1)),
                ('pressure_build_up_time', models.FloatField(default=0.05)),
            ],
        ),
        migrations.CreateModel(
            name='ThermoformingVerificationSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculate_permeability', models.BooleanField(default=False)),
                ('compare_with_other_laminates_and_lids', models.BooleanField(default=False)),
                ('analysis_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.analysisdetail')),
                ('thermoforming_cavity_parameters', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.thermoformingcavityparameters')),
                ('thermoforming_process_parameters', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.thermoformingprocessparameters')),
            ],
        ),
    ]
