# Generated by Django 4.2.4 on 2023-10-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermoformingverificationsimulation',
            name='thermoforming_cavity_parameters',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.thermoformingcavityparameters'),
        ),
        migrations.AlterField(
            model_name='thermoformingverificationsimulation',
            name='thermoforming_process_parameters',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.thermoformingprocessparameters'),
        ),
    ]
