# Generated by Django 4.2.4 on 2023-11-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0029_layerstructure_released_for_thermoforming_lid'),
        ('forms', '0003_remove_thermoformingprocessparameters_laminate_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermoformingverificationsimulation',
            name='cavity_materials',
            field=models.ManyToManyField(default=None, null=True, related_name='cavity_materials', to='material_data.layerstructure'),
        ),
        migrations.AddField(
            model_name='thermoformingverificationsimulation',
            name='lid_materials',
            field=models.ManyToManyField(default=None, null=True, related_name='lid_materials', to='material_data.layerstructure'),
        ),
    ]
