# Generated by Django 4.2.4 on 2023-11-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_thermoformingplugparameters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thermoformingverificationsimulation',
            old_name='thermoforming_cavity_parameters',
            new_name='cavity_parameters',
        ),
        migrations.RenameField(
            model_name='thermoformingverificationsimulation',
            old_name='thermoforming_plug_parameters',
            new_name='plug_parameters',
        ),
        migrations.RenameField(
            model_name='thermoformingverificationsimulation',
            old_name='thermoforming_process_parameters',
            new_name='process_parameters',
        ),
    ]
