# Generated by Django 4.2.4 on 2023-11-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0030_thermoformingplug'),
        ('forms', '0007_rename_thermoforming_cavity_parameters_thermoformingverificationsimulation_cavity_parameters_and_mor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThermoformingVerificationSimulation',
            new_name='ThermoformingSimulation',
        ),
        migrations.AddField(
            model_name='thermoformingplugparameters',
            name='length',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
