# Generated by Django 4.2.4 on 2023-10-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DensityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('thickness', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PermeabilityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('wvtr', 'WVTR'), ('otr', 'OTR')], max_length=4)),
                ('temperature', models.FloatField()),
                ('RH', models.FloatField()),
                ('transmission_rate', models.FloatField()),
                ('diffusivity', models.FloatField(default=None, null=True)),
                ('solubility', models.FloatField(default=None, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permeability_data', to='material_data.material')),
            ],
        ),
        migrations.CreateModel(
            name='StressStrainCurveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain_rate', models.FloatField()),
                ('temperature', models.FloatField()),
                ('direction', models.CharField(choices=[('MD', 'MD'), ('CD', 'CD')], max_length=2)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_strain_curve_data', to='material_data.material')),
            ],
        ),
        migrations.CreateModel(
            name='YoungsModulusCurveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poissons_ratio', models.FloatField()),
                ('direction', models.CharField(choices=[('MD', 'MD'), ('CD', 'CD')], max_length=2)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youngs_modulus_curve_data', to='material_data.material')),
            ],
        ),
        migrations.CreateModel(
            name='YoungsModulusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youngs_modulus', models.FloatField()),
                ('poissons_ratio', models.FloatField()),
                ('temperature', models.FloatField()),
                ('direction', models.CharField(choices=[('MD', 'MD'), ('CD', 'CD')], max_length=2)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youngs_modulus_data', to='material_data.material')),
            ],
        ),
        migrations.CreateModel(
            name='YoungsModulusCurvePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('youngs_modulus', models.FloatField()),
                ('youngs_modulus_curve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_data.youngsmoduluscurvedata')),
            ],
        ),
        migrations.CreateModel(
            name='ThermoformingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density_data', models.ManyToManyField(to='material_data.densitydata')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thermoforming_data', to='material_data.material')),
                ('permeability_data', models.ManyToManyField(to='material_data.permeabilitydata')),
                ('stress_strain_curve_data', models.ManyToManyField(to='material_data.stressstraincurvedata')),
                ('youngs_modulus_curve_data', models.ManyToManyField(to='material_data.youngsmoduluscurvedata')),
                ('youngs_modulus_data', models.ManyToManyField(to='material_data.youngsmodulusdata')),
            ],
        ),
        migrations.CreateModel(
            name='StressStrainCurvePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stress', models.FloatField()),
                ('strain', models.FloatField()),
                ('stress_strain_curve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_data.stressstraincurvedata')),
            ],
        ),
        migrations.CreateModel(
            name='Laminate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('materials', models.ManyToManyField(related_name='laminates', to='material_data.material')),
            ],
        ),
        migrations.AddField(
            model_name='densitydata',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='density_data', to='material_data.material'),
        ),
    ]
