# Generated by Django 4.2.4 on 2023-10-23 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0002_delete_laminate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laminate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaminateMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('laminate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_data.laminate')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_data.material')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('material', 'laminate', 'order')},
            },
        ),
        migrations.AddField(
            model_name='laminate',
            name='materials',
            field=models.ManyToManyField(through='material_data.LaminateMaterial', to='material_data.material'),
        ),
    ]
