# Generated by Django 4.2.4 on 2023-10-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0004_remove_laminate_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youngsmoduluscurvepoint',
            name='youngs_modulus_curve',
        ),
        migrations.RemoveField(
            model_name='thermoformingdata',
            name='youngs_modulus_curve_data',
        ),
        migrations.DeleteModel(
            name='YoungsModulusCurveData',
        ),
        migrations.DeleteModel(
            name='YoungsModulusCurvePoint',
        ),
    ]
