# Generated by Django 4.2.4 on 2023-10-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0005_remove_youngsmoduluscurvepoint_youngs_modulus_curve_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laminate',
            new_name='LayerStructure',
        ),
    ]
