# Generated by Django 4.2.4 on 2023-10-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0006_rename_laminate_layerstructure'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaminateMaterial',
            new_name='LayerStructureOrder',
        ),
    ]
