# Generated by Django 4.2.4 on 2023-10-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0007_rename_laminatematerial_layerstructureorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layerstructureorder',
            old_name='laminate',
            new_name='layer_structure',
        ),
        migrations.AlterUniqueTogether(
            name='layerstructureorder',
            unique_together={('material', 'layer_structure', 'order')},
        ),
    ]
