# Generated by Django 4.2.4 on 2023-10-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0009_rename_layerstructureorder_materialorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StressStrainCurveData',
            new_name='TensileCurveData',
        ),
    ]
