# Generated by Django 4.2.4 on 2023-10-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0010_rename_stressstraincurvedata_tensilecurvedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thermoformingdata',
            old_name='stress_strain_curve_data',
            new_name='tensile_data',
        ),
    ]
