# Generated by Django 4.2.4 on 2023-10-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0011_rename_stress_strain_curve_data_thermoformingdata_tensile_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StressStrainCurvePoint',
            new_name='TensileCurvePoint',
        ),
    ]
