# Generated by Django 4.2.4 on 2023-10-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0012_rename_stressstraincurvepoint_tensilecurvepoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tensilecurvepoint',
            old_name='stress_strain_curve',
            new_name='tensile_curve',
        ),
    ]
