# Generated by Django 4.2.4 on 2023-10-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0013_rename_stress_strain_curve_tensilecurvepoint_tensile_curve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thermoformingdata',
            old_name='tensile_data',
            new_name='tensile_curve_data',
        ),
        migrations.AlterField(
            model_name='tensilecurvedata',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tensile_curve_data', to='material_data.material'),
        ),
    ]
