# Generated by Django 4.2.4 on 2023-10-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0014_rename_tensile_data_thermoformingdata_tensile_curve_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permeabilitydata',
            name='type',
        ),
    ]
