# Generated by Django 4.2.4 on 2023-10-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0017_rename_transmission_rate_wvtrdata_wvtr'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerstructure',
            name='available_for_thermoforming',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
