# Generated by Django 4.2.4 on 2023-10-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0018_layerstructure_available_for_thermoforming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerstructure',
            name='available_for_thermoforming',
            field=models.BooleanField(default=False),
        ),
    ]
