# Generated by Django 4.2.4 on 2023-10-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0019_alter_layerstructure_available_for_thermoforming'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layerstructure',
            old_name='available_for_thermoforming',
            new_name='released_for_thermoforming',
        ),
    ]
