# Generated by Django 4.2.4 on 2023-10-30 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0020_rename_available_for_thermoforming_layerstructure_released_for_thermoforming'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('RH', models.FloatField()),
                ('OTR', models.FloatField()),
                ('diffusivity', models.FloatField(default=None, null=True)),
                ('solubility', models.FloatField(default=None, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otr_data', to='material_data.material')),
            ],
        ),
    ]
