# Generated by Django 4.2.4 on 2023-10-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0022_thermoformingdata_otr_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DruckerPragerCurveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input1', models.FloatField()),
                ('input2', models.FloatField()),
                ('input3', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drucker_prager_curve_data', to='material_data.material')),
            ],
        ),
        migrations.CreateModel(
            name='DruckerPragerCurvePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stress', models.FloatField()),
                ('strain', models.FloatField()),
                ('drucker_prager_curve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_data.druckerpragercurvedata')),
            ],
        ),
    ]
