# Generated by Django 4.2.4 on 2023-10-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0023_druckerpragercurvedata_druckerpragercurvepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='druckerpragercurvedata',
            name='direction',
            field=models.CharField(choices=[('MD', 'MD'), ('CD', 'CD')], default='MD', max_length=2),
            preserve_default=False,
        ),
    ]
