# Generated by Django 4.2.4 on 2023-10-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0025_thermoformingliddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdformingStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('friction_coefficient', models.FloatField()),
            ],
        ),
    ]
