# Generated by Django 4.2.4 on 2023-10-31 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0026_coldformingstamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdformingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drucker_prager_curve_data', models.ManyToManyField(to='material_data.druckerpragercurvedata')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coldforming_data', to='material_data.material')),
                ('tensile_curve_data', models.ManyToManyField(to='material_data.tensilecurvedata')),
                ('youngs_modulus_data', models.ManyToManyField(to='material_data.youngsmodulusdata')),
            ],
        ),
    ]
