# Generated by Django 4.2.4 on 2023-10-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0027_coldformingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerstructure',
            name='released_for_coldforming',
            field=models.BooleanField(default=False),
        ),
    ]
