# Generated by Django 4.2.4 on 2023-10-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_data', '0028_layerstructure_released_for_coldforming'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerstructure',
            name='released_for_thermoforming_lid',
            field=models.BooleanField(default=False),
        ),
    ]
